version: "3.8"

services:
  database:
    image: "mysql:8.0.30-debian"
    environment:
      - MYSQL_ROOT_PASSWORD=asdd
      - MYSQL_DATABASE=PMS
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - DB_CONNECTION=mysql
      - DB_HOST=database
    #   - DB_PORT=3306
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=asdd
    ports:
      - 8000:8000
    volumes:
    - ./:/app
    - /app/node_modules
    - /app/vendor
    entrypoint: ./start.sh
    # command: tail -F /dev/null



