version: "3.8"

services:
  database:
    image: "mysql:8.0.30-debian"
    env_file:
      - .env
    # ports:
      # - "3306:3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
    - ./:/app
    - /app/node_modules
    - /app/vendor
    # - /app/start.sh
    # - /app/wait-for-it.sh
    entrypoint: ./start.sh




